### ISSUE TITLE
Way to prevent entering interactive mode when run from scripts

### ISSUE THREAD

**Issue by ceresek** [d-iii-s/msim#12]
Code can use special instruction to enter interactive mode. When run from script, this usually creates issues (simulation may appear to hang when in fact it is just waiting for input). We should have a way to avoid this:
- an extra command line switch that would make any attempt to enter interactive mode exit the simulator
- checking whether we have interactive input using `isatty`
- ... ?

**Comment by lbulej** [comment]
The check using `isatty()` looks like a good solution...
