### ISSUE TITLE
Maybe make printer device flush output immediately ?

### ISSUE THREAD

**Issue by ceresek** [D-iii-S/msim#3]
The current implementation of the printer device (dprinter) flushes output inside printer_step4k, that is, only every 4096 simulator steps. Possibly, this was done to improve simulation speed, but as a result the print output is not visible when single stepping using the gdb interface. This is not a problem in the msim interface, because it uses the same output as the machine and flushes during command prompts.

(I can do the change, the reason for the ticket is I'm not sure there aren't other reasons for the delayed flush.)

**Comment by vhotspur** [comment]
IMHO it was only for performance reasons. I think it is okay to flush it always. Or maybe flush it only when `machine_interactive == true`?
