### ISSUE TITLE
Documentation for command break is wrong

### ISSUE THREAD

**Issue by KronwarsCZ** [d-iii-s/msim#55]
Hi everyone,  
I would like to report an issue with wrong documentation, section System commands -> break [here](https://msim.readthedocs.io/en/latest/reference/system_commands.html#break-add-memory-breakpoint).

Documentation shows syntax for break:  `break address type`, which is incorrect for msim 2.2.0, where break syntax is this:
```
[msim] help break
Add a new physical memory breakpoint
Syntax: break <addr> <cnt> <type>
        <addr> memory address
        <cnt> count
        <type> Read or write breakpoint
```

The documentation then describes parameters `address` and `count` instead of `type`.

**Comment by vhotspur** [comment]
Thanks for the report, the fix is already visible in the online documentation.
